[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false

[params]
baseURL = "https://payback159.github.io"
title = "Alexander Jelinek"
author = "Alexander Jelinek"
description = "Call me Alex"
profilePicture = "images/profile.gif"

  [[params.socialIcons]]
  icon = "fab fa-github"
  title = "GitHub"
  url = "https://github.com/Payback159"

  [[params.socialIcons]]
  icon = "fab fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/alexanderjelinek/"

  [[params.socialIcons]]
  icon = "fab fa-xing"
  title = "Xing"
  url = "https://www.xing.com/profile/Alexander_Jelinek4/portfolio"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

#  [[menu.main]]
#  name = "About"
#  weight = 300
#  identifier = "about"
#  url = "/about/"

[related]
  includeNewer = true
  threshold = 80
  toLower = true

  [[related.indices]]
  name = 'keywords'
  weight = 100

  [[related.indices]]
  name = 'tags'
  weight = 80